### ISSUE TITLE
He's really aggresive man.. Ah, fuck, what am I doing, I don't have a fucking jugg, oh wait, nevermind. Oh, fuck me dude. Fuck. slap SON OF A BITCH! This guy is a fucking retard and I lost to this horseshit, man. Ok, let's rematch, let's see if he rematches. Good game? My ass! That was the shittiest fucking micro I've ever seen.

### ISSUE THREAD

**Issue by DannyParker0001** [KosmicShovel/BTD6-Mods#2]
He's really aggresive man..
Ah, fuck, what am I doing, I don't have a fucking jugg, oh wait, nevermind.
Oh, fuck me dude.
Fuck.
slap
SON OF A BITCH!
This guy is a fucking retard and I lost to this horseshit, man.
Ok, let's rematch, let's see if he rematches.
Good game? My ass! That was the shittiest fucking micro I've ever seen.

**Comment by MatthewOGuerra** [comment]
Ive noticed youve failed your recent math exam, please respond back soon.
